export interface ErrorResponse {
  code: string;
  message: string;
}

type Locale = 'tc' | 'en';

export type BilingualFormat = Record<Locale, string>;
export type BilingualArrayFormat = Record<Locale, string[]>;

export type OrderType = 'DESC' | 'ASC';

// ! May hard code in frontend
export interface MtrType {
  station:
    | 'lamTin'
    | 'kwunTong'
    | 'ngauTauKok'
    | 'kowloonBay'
    | 'choiHung'
    | 'diamondHill'
    | 'wongTaiSin'
    | 'lokFu'
    | 'kowloonTong'
    | 'shekKipMei'
    | 'princeEdward'
    | 'mongKok'
    | 'yauMaTei'
    | 'hoManTin'
    | 'tsuenWan'
    | 'taiWoHau'
    | 'hoManTin'
    | 'kwaiHing'
    | 'kwaiFong'
    | 'laiKing'
    | 'meiFoo'
    | 'laiChiKok'
    | 'cheungShaWan'
    | 'shamShuiPo'
    | 'princeEdward'
    | 'mongKok'
    | 'yauMaTei'
    | 'jordan'
    | 'tsimShaTsui'
    | 'knnedyTown'
    | 'princeEdward'
    | 'hku'
    | 'saiYingPun'
    | 'sheungWan'
    | 'central'
    | 'admiralty'
    | 'wanChai'
    | 'causewayBay'
    | 'tinHau'
    | 'fortressHill'
    | 'northPoint'
    | 'qarryBay'
    | 'taiKoo'
    | 'saiWanHo'
    | 'shauKeiWan'
    | 'saiWanHo'
    | 'hengFaChuen'
    | 'chaiWan'
    | 'admiralty'
    | 'oceanPark'
    | 'wongChukHang'
    | 'leiTung'
    | 'southHorizons'
    | 'chaiWan'
    | 'lohasPark'
    | 'poLam'
    | 'hangHau'
    | 'tseungKwanO'
    | 'tiuKengLeng'
    | 'yauTong'
    | 'hongKong'
    | 'kowloon'
    | 'namCheong'
    | 'laiKing'
    | 'tsingYi'
    | 'sunnyBay'
    | 'disneylandResort'
    | 'tungChung'
    | 'laiKing'
    | 'hungHom'
    | 'mongKokEast'
    | 'kowloonTong'
    | 'taiWai'
    | 'shaTin'
    | 'foTan'
    | 'racecourse'
    | 'uiversity'
    | 'taiPoMarket'
    | 'taiWo'
    | 'fanling'
    | 'sheungShui'
    | 'loWu'
    | 'lokMahau'
    | 'tuenMun'
    | 'siuHong'
    | 'tinShuiWai'
    | 'longPing'
    | 'yuenLong'
    | 'kamSheungRoad'
    | 'tsuenWanWest'
    | 'Mei Foo'
    | 'Nam Cheong'
    | 'austin'
    | 'eastTsimShaTsui'
    | 'hoManTin'
    | 'toKwaWan'
    | 'sungWongToi'
    | 'kaiTak'
    | 'diamondHill'
    | 'hinKeng'
    | 'taiWai'
    | 'cheKungTemple'
    | 'shaTinWai'
    | 'cityOne'
    | 'shekMun'
    | 'taiShuiHang'
    | 'hengOn'
    | 'maOnShan'
    | 'wuKaiSha';
  exit:
    | 'A'
    | 'B'
    | 'C'
    | 'D'
    | 'E'
    | 'F'
    | 'G'
    | 'H'
    | 'I'
    | 'J'
    | 'K'
    | 'L'
    | 'M'
    | 'N'
    | 'O'
    | 'P'
    | 'Q'
    | 'R'
    | 'S'
    | 'T'
    | 'U'
    | 'V'
    | 'W'
    | 'X'
    | 'Y'
    | 'Z';
}

export interface Timeslot {
  fromTime: string;
  toTime: string;
}
export type BusinessHours = Partial<
  Record<'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun', Timeslot[]>
>;
